### ISSUE TITLE
hold bug

### ISSUE THREAD

**Issue by tonyxdsu** [CodeTheChangeUBC/OLPC#64]
I can't recreate it.
But it happened when holding a block as the first thing done in the game

Traceback (most recent call last):
  File "game.py", line 601, in <module>

  File "game.py", line 512, in runGame
    # drawing bg
  File "game.py", line 84, in tick
    pos_y += BLOCK_SIZE
  File "game.py", line 141, in checkGameOver
    def checkCollision():
  File "game.py", line 396, in gameOver
    myfont = pygame.font.SysFont('Comic Sans MS', 30)
  File "game.py", line 512, in runGame
    # drawing bg
  File "game.py", line 84, in tick
    pos_y += BLOCK_SIZE
  File "game.py", line 141, in checkGameOver
    def checkCollision():
  File "game.py", line 396, in gameOver
    myfont = pygame.font.SysFont('Comic Sans MS', 30)
  File "game.py", line 489, in runGame
    elif event.key == pygame.K_p:
  File "game.py", line 84, in tick
    pos_y += BLOCK_SIZE
  File "game.py", line 141, in checkGameOver
    def checkCollision():
  File "game.py", line 396, in gameOver
    myfont = pygame.font.SysFont('Comic Sans MS', 30)
  File "game.py", line 550, in runGame

  File "game.py", line 245, in getShadowDifference
    return difference
IndexError: list index out of range

**Comment by tonyxdsu** [comment]
I don't know what triggered this but I got it again. Holding right away.

Traceback (most recent call last):
  File "game.py", line 965, in <module>
    main()
  File "game.py", line 961, in main
    runGame()
  File "game.py", line 673, in runGame
    difference = getShadowDifference(block.getPerimeter())
  File "game.py", line 270, in getShadowDifference
    if landed[currX][y] != None and difference > y * BLOCK_SIZE - blockList[i].getY() - BLOCK_SIZE:  # - 14:
IndexError: list index out of range

**Comment by tonyxdsu** [comment]
Oh it's just holding too quickly when the game runs

**Comment by tonyxdsu** [comment]
Traceback (most recent call last):
  File ".\Metris.py", line 1543, in <module>
    main()
  File ".\Metris.py", line 1539, in main
    main_menu.mainloop(pygame.event.get())
  File "C:\Users\TomoXPS\Documents\GitHub\CodeTheChange\OLPC\Metris\pygameMenu\menu.py", line 611, in mainloop
    if self._main():
  File "C:\Users\TomoXPS\Documents\GitHub\CodeTheChange\OLPC\Metris\pygameMenu\menu.py", line 538, in _main
    self._select()
  File "C:\Users\TomoXPS\Documents\GitHub\CodeTheChange\OLPC\Metris\pygameMenu\menu.py", line 722, in _select
    option()
  File ".\Metris.py", line 1405, in play_function
    runGame()
  File ".\Metris.py", line 815, in runGame
    hold(blockSet, nextBlocks)
  File ".\Metris.py", line 404, in hold
    offset_x += getOffsetX(getBlockType(holdBlock))
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
